const matches = [
  { id: "A1", group: "Grupp A", teamA: "Mexiko", teamB: "Sydafrika", flagA: "🇲🇽", flagB: "🇿🇦" },
  { id: "A2", group: "Grupp A", teamA: "Sydkorea", teamB: "Tjeckien", flagA: "🇰🇷", flagB: "🇨🇿" },
  { id: "A3", group: "Grupp A", teamA: "Tjeckien", teamB: "Sydafrika", flagA: "🇨🇿", flagB: "🇿🇦" },
  { id: "A4", group: "Grupp A", teamA: "Mexiko", teamB: "Sydkorea", flagA: "🇲🇽", flagB: "🇰🇷" },
  { id: "A5", group: "Grupp A", teamA: "Tjeckien", teamB: "Mexiko", flagA: "🇨🇿", flagB: "🇲🇽" },
  { id: "A6", group: "Grupp A", teamA: "Sydafrika", teamB: "Sydkorea", flagA: "🇿🇦", flagB: "🇰🇷" },

  { id: "B1", group: "Grupp B", teamA: "Kanada", teamB: "Bosnien och Hercegovina", flagA: "🇨🇦", flagB: "🇧🇦" },
  { id: "B2", group: "Grupp B", teamA: "Qatar", teamB: "Schweiz", flagA: "🇶🇦", flagB: "🇨🇭" },
  { id: "B3", group: "Grupp B", teamA: "Schweiz", teamB: "Bosnien och Hercegovina", flagA: "🇨🇭", flagB: "🇧🇦" },
  { id: "B4", group: "Grupp B", teamA: "Kanada", teamB: "Qatar", flagA: "🇨🇦", flagB: "🇶🇦" },
  { id: "B5", group: "Grupp B", teamA: "Schweiz", teamB: "Kanada", flagA: "🇨🇭", flagB: "🇨🇦" },
  { id: "B6", group: "Grupp B", teamA: "Bosnien och Hercegovina", teamB: "Qatar", flagA: "🇧🇦", flagB: "🇶🇦" },

  { id: "C1", group: "Grupp C", teamA: "Brasilien", teamB: "Marocko", flagA: "🇧🇷", flagB: "🇲🇦" },
  { id: "C2", group: "Grupp C", teamA: "Haiti", teamB: "Skottland", flagA: "🇭🇹", flagB: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "C3", group: "Grupp C", teamA: "Skottland", teamB: "Marocko", flagA: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", flagB: "🇲🇦" },
  { id: "C4", group: "Grupp C", teamA: "Brasilien", teamB: "Haiti", flagA: "🇧🇷", flagB: "🇭🇹" },
  { id: "C5", group: "Grupp C", teamA: "Skottland", teamB: "Brasilien", flagA: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", flagB: "🇧🇷" },
  { id: "C6", group: "Grupp C", teamA: "Marocko", teamB: "Haiti", flagA: "🇲🇦", flagB: "🇭🇹" },

  { id: "D1", group: "Grupp D", teamA: "USA", teamB: "Paraguay", flagA: "🇺🇸", flagB: "🇵🇾" },
  { id: "D2", group: "Grupp D", teamA: "Australien", teamB: "Turkiet", flagA: "🇦🇺", flagB: "🇹🇷" },
  { id: "D3", group: "Grupp D", teamA: "USA", teamB: "Australien", flagA: "🇺🇸", flagB: "🇦🇺" },
  { id: "D4", group: "Grupp D", teamA: "Turkiet", teamB: "Paraguay", flagA: "🇹🇷", flagB: "🇵🇾" },
  { id: "D5", group: "Grupp D", teamA: "Turkiet", teamB: "USA", flagA: "🇹🇷", flagB: "🇺🇸" },
  { id: "D6", group: "Grupp D", teamA: "Paraguay", teamB: "Australien", flagA: "🇵🇾", flagB: "🇦🇺" },

  { id: "E1", group: "Grupp E", teamA: "Tyskland", teamB: "Curaçao", flagA: "🇩🇪", flagB: "🇨🇼" },
  { id: "E2", group: "Grupp E", teamA: "Elfenbenskusten", teamB: "Ecuador", flagA: "🇨🇮", flagB: "🇪🇨" },
  { id: "E3", group: "Grupp E", teamA: "Tyskland", teamB: "Elfenbenskusten", flagA: "🇩🇪", flagB: "🇨🇮" },
  { id: "E4", group: "Grupp E", teamA: "Ecuador", teamB: "Curaçao", flagA: "🇪🇨", flagB: "🇨🇼" },
  { id: "E5", group: "Grupp E", teamA: "Curaçao", teamB: "Elfenbenskusten", flagA: "🇨🇼", flagB: "🇨🇮" },
  { id: "E6", group: "Grupp E", teamA: "Ecuador", teamB: "Tyskland", flagA: "🇪🇨", flagB: "🇩🇪" },

  { id: "F1", group: "Grupp F", teamA: "Nederländerna", teamB: "Japan", flagA: "🇳🇱", flagB: "🇯🇵" },
  { id: "F2", group: "Grupp F", teamA: "Sverige", teamB: "Tunisien", flagA: "🇸🇪", flagB: "🇹🇳" },
  { id: "F3", group: "Grupp F", teamA: "Nederländerna", teamB: "Sverige", flagA: "🇳🇱", flagB: "🇸🇪" },
  { id: "F4", group: "Grupp F", teamA: "Tunisien", teamB: "Japan", flagA: "🇹🇳", flagB: "🇯🇵" },
  { id: "F5", group: "Grupp F", teamA: "Japan", teamB: "Sverige", flagA: "🇯🇵", flagB: "🇸🇪" },
  { id: "F6", group: "Grupp F", teamA: "Tunisien", teamB: "Nederländerna", flagA: "🇹🇳", flagB: "🇳🇱" },

  { id: "G1", group: "Grupp G", teamA: "Belgien", teamB: "Egypten", flagA: "🇧🇪", flagB: "🇪🇬" },
  { id: "G2", group: "Grupp G", teamA: "Iran", teamB: "Nya Zeeland", flagA: "🇮🇷", flagB: "🇳🇿" },
  { id: "G3", group: "Grupp G", teamA: "Belgien", teamB: "Iran", flagA: "🇧🇪", flagB: "🇮🇷" },
  { id: "G4", group: "Grupp G", teamA: "Nya Zeeland", teamB: "Egypten", flagA: "🇳🇿", flagB: "🇪🇬" },
  { id: "G5", group: "Grupp G", teamA: "Egypten", teamB: "Iran", flagA: "🇪🇬", flagB: "🇮🇷" },
  { id: "G6", group: "Grupp G", teamA: "Nya Zeeland", teamB: "Belgien", flagA: "🇳🇿", flagB: "🇧🇪" },

  { id: "H1", group: "Grupp H", teamA: "Spanien", teamB: "Kap Verde", flagA: "🇪🇸", flagB: "🇨🇻" },
  { id: "H2", group: "Grupp H", teamA: "Saudiarabien", teamB: "Uruguay", flagA: "🇸🇦", flagB: "🇺🇾" },
  { id: "H3", group: "Grupp H", teamA: "Spanien", teamB: "Saudiarabien", flagA: "🇪🇸", flagB: "🇸🇦" },
  { id: "H4", group: "Grupp H", teamA: "Uruguay", teamB: "Kap Verde", flagA: "🇺🇾", flagB: "🇨🇻" },
  { id: "H5", group: "Grupp H", teamA: "Kap Verde", teamB: "Saudiarabien", flagA: "🇨🇻", flagB: "🇸🇦" },
  { id: "H6", group: "Grupp H", teamA: "Uruguay", teamB: "Spanien", flagA: "🇺🇾", flagB: "🇪🇸" },

  { id: "I1", group: "Grupp I", teamA: "Frankrike", teamB: "Senegal", flagA: "🇫🇷", flagB: "🇸🇳" },
  { id: "I2", group: "Grupp I", teamA: "Irak", teamB: "Norge", flagA: "🇮🇶", flagB: "🇳🇴" },
  { id: "I3", group: "Grupp I", teamA: "Frankrike", teamB: "Irak", flagA: "🇫🇷", flagB: "🇮🇶" },
  { id: "I4", group: "Grupp I", teamA: "Norge", teamB: "Senegal", flagA: "🇳🇴", flagB: "🇸🇳" },
  { id: "I5", group: "Grupp I", teamA: "Norge", teamB: "Frankrike", flagA: "🇳🇴", flagB: "🇫🇷" },
  { id: "I6", group: "Grupp I", teamA: "Senegal", teamB: "Irak", flagA: "🇸🇳", flagB: "🇮🇶" },

  { id: "J1", group: "Grupp J", teamA: "Argentina", teamB: "Algeriet", flagA: "🇦🇷", flagB: "🇩🇿" },
  { id: "J2", group: "Grupp J", teamA: "Österrike", teamB: "Jordanien", flagA: "🇦🇹", flagB: "🇯🇴" },
  { id: "J3", group: "Grupp J", teamA: "Argentina", teamB: "Österrike", flagA: "🇦🇷", flagB: "🇦🇹" },
  { id: "J4", group: "Grupp J", teamA: "Jordanien", teamB: "Algeriet", flagA: "🇯🇴", flagB: "🇩🇿" },
  { id: "J5", group: "Grupp J", teamA: "Algeriet", teamB: "Österrike", flagA: "🇩🇿", flagB: "🇦🇹" },
  { id: "J6", group: "Grupp J", teamA: "Jordanien", teamB: "Argentina", flagA: "🇯🇴", flagB: "🇦🇷" },

  { id: "K1", group: "Grupp K", teamA: "Portugal", teamB: "DR Kongo", flagA: "🇵🇹", flagB: "🇨🇩" },
  { id: "K2", group: "Grupp K", teamA: "Uzbekistan", teamB: "Colombia", flagA: "🇺🇿", flagB: "🇨🇴" },
  { id: "K3", group: "Grupp K", teamA: "Portugal", teamB: "Uzbekistan", flagA: "🇵🇹", flagB: "🇺🇿" },
  { id: "K4", group: "Grupp K", teamA: "Colombia", teamB: "DR Kongo", flagA: "🇨🇴", flagB: "🇨🇩" },
  { id: "K5", group: "Grupp K", teamA: "Colombia", teamB: "Portugal", flagA: "🇨🇴", flagB: "🇵🇹" },
  { id: "K6", group: "Grupp K", teamA: "DR Kongo", teamB: "Uzbekistan", flagA: "🇨🇩", flagB: "🇺🇿" },

  { id: "L1", group: "Grupp L", teamA: "England", teamB: "Kroatien", flagA: "🏴", flagB: "🇭🇷" },
  { id: "L2", group: "Grupp L", teamA: "Ghana", teamB: "Panama", flagA: "🇬🇭", flagB: "🇵🇦" },
  { id: "L3", group: "Grupp L", teamA: "England", teamB: "Ghana", flagA: "🏴", flagB: "🇬🇭" },
  { id: "L4", group: "Grupp L", teamA: "Panama", teamB: "Kroatien", flagA: "🇵🇦", flagB: "🇭🇷" },
  { id: "L5", group: "Grupp L", teamA: "Panama", teamB: "England", flagA: "🇵🇦", flagB: "🏴" },
  { id: "L6", group: "Grupp L", teamA: "Kroatien", teamB: "Ghana", flagA: "🇭🇷", flagB: "🇬🇭" }
];